### ISSUE TITLE
question about planned features

### ISSUE THREAD

**Issue by ldpr** [h44z/wg-portal#145]
Hello!

I just have a quick question, this tool looks _absolutely perfect_ for our use case, except for one thing. We'd like to run 5-8 servers with wireguard on them and if possible, have them managed from one location.

Is that something you'd considered in the past or would it even be possible with the current codebase?
Granted we could run multiple instances too but figured it'd be better to ask beforehand just in case.

Thank you!

**Comment by h44z** [comment]
You can already manage multiple WireGuard interfaces in one WireGuard Portal instance. If you want to manage multiple different host machines with WireGuard interfaces, this is currently not supported nor planned.

**Comment by xpufx** [comment]
@h44z In my current setup configured on opnsense, i have an interface wg0 dedicated to employees and another wg1 dedicated to external users. Their allowed IPs and firewall restrictions are different. Since there's no self service there, this was working fine.

As far as I can tell when I enable self provisioning in wgportal, it's allowing all interfaces. Right now I am considering running one instance of wgportal for each interface. (I tested it a bit while keeping this post as a draft and so far so good. A bit of a manual job keeping interface names and ports separate though)

Is any kind of granular permissions based on interface in the roadmap?

**Comment by h44z** [comment]
@xpufx not for v2.0, maybe for v2.x
