### ISSUE TITLE
Any way to drop to non-root user in the docker-image?

### ISSUE THREAD

**Issue by EugenMayer** [h44z/wg-portal#64]
The GUI is one of the current attack-vectors on the VPN gateways and i would love to reduce this if possible.

For this, would propose dropping the privileges with `gosu` or alikes to a non-root user, since the root user is really the most problematic thing in the concept, which can overtake the entire host (and thus all networks).

AFAIR wg-portal does not
 - create custom IPtables entries (like wg-easy/wg-ui)
 - create any routes

All it does it read/write
 - /etc/wireguard
 - SQL database

The former is owner by root on the server and this is what we would need to change, letting them be owner by some uid/gid we share with the container (non world readable for obvious reasons). 

The Go server/webserver binds on 8123 already, so non privileged port rang (perfect).

That said, i see not too much effort for a significant security gain. @h44z what is your take on that? 

If you like the idea conceptually i do not see any hurdles i missed, i could provide a PR for that - let me know.

**Comment by h44z** [comment]
wg-portal uses https://github.com/WireGuard/wgctrl-go to configure the interfaces. /etc/wireguard files are just written so that the WG tunnels can work without wg-portal.
In principle I agree with you on the point that the GUI is one of the current attack-vectors. But in order to conveniently configure kernel WG interfaces, a root user is needed. Also, version 2.0 of wg-portal will support the creation and management of completely new WG interfaces, which again needs root permissions.

If there is a good way to achieve the same functionality without root privileges, I am open for PRs =)

**Comment by EugenMayer** [comment]
i guess the only way to go here is to use sudo + scoped scripts.

So run the GUI under `wgportal` and if you need to create interfaces call '/usr/local/bin/wg-portal-create-interface $args'
and add /usr/local/bin/wg-portal-create-interface to password-less sudo.

This way the scope of the attacker is limited since you cannot entirely escalate into a free root shell with all the ops.

Any thoughts?

**Comment by h44z** [comment]
Yeah this is one possible solution, I will check this again once v2 is in an usable state.

**Comment by UtkarshVerma** [comment]
Hi, first thank you for the project. Did this issue see any progress?

**Comment by h44z** [comment]
Hi @UtkarshVerma, in general, you still need root permissions to manage interfaces and WireGuard settings. But since version 2.1, it is possible to add custom backends. Currently, only one new backend for Mikrotik is implemented. With an external backend, you can start wgportal as non-root user. I currently have no plans to implement a local backend that does not require wg-portal to start as root, but I am very happy to merge any PRs :)
